### ISSUE TITLE
Comentario sobre tu implementación de MDLinks

### ISSUE THREAD

**Issue by lizzie136** [florenciasilva/cdmx-2018-01-FE-markdown#7]
Tengo algunos comentarios sobre el código de tu archivo markdown: 

 - En varias partes estás usando `let` pero no es algo que vas a reescribir en el futuro. Por ejemplo https://github.com/florenciasilva/modulo-npm-markdown-links/blob/96cfdfbf1e10335ce6ca015869209b216091513d/markdown.js#L14 en esos casos sería más adecuado usar `const`

- Aquí podrías usar string literal o template strings https://github.com/florenciasilva/modulo-npm-markdown-links/blob/96cfdfbf1e10335ce6ca015869209b216091513d/markdown.js#L53

- No llegué a ver ningún test 😢

**Comment by florenciasilva** [comment]
¡Muchas gracias, Eli! Voy a retomarlo para que quede bien bien 💪
